grails-app/controllers/com/billing/controller/AuthController.groovy
package com.billing.controller

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.crypto.hash.Sha512Hash
import org.apache.shiro.grails.ConfigUtils
import org.apache.shiro.web.util.WebUtils

import com.billing.domain.Role
import com.billing.domain.User

class AuthController {
	def shiroSecurityManager
	def userService
	
	def index = { redirect(action: "login", params: params) }

	def login = {
		return [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
	}

	def forgotPassword = {
		
	}
	
	def register = {
		
	}
	
	def registerUser(){
		def userInstance = new User(params)
		def userRole = Role.findByName("Company")
		userInstance.addToRoles(userRole)
		
		if (!userInstance.validate()) {
			render(view: "register", model: [userInstance: userInstance])
			return
		}else{
			userInstance.passwordHash = new Sha512Hash(userInstance.passwordHash).toHex()
			println "Create User :" + userInstance
			userService.createUser(userInstance)
			flash.successMessage = "You have registerd to Billastick successfully. Kindly proceed to login."
		}
		
		redirect(action:'login')
		//redirect(controller:'index')

	}
	def signIn = {
		def authToken = new UsernamePasswordToken(params.username, params.password as String)

		// Support for "remember me"
		if (params.rememberMe) {
			authToken.rememberMe = true
		}
		
		// If a controller redirected to this page, redirect back
		// to it. Otherwise redirect to the root URI.
		def targetUri = params.targetUri ?: "/"
		
		// Handle requests saved by Shiro filters.
		def savedRequest = WebUtils.getSavedRequest(request)
		if (savedRequest) {
			targetUri = savedRequest.requestURI - request.contextPath
			if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
		}
		
		try{
			// Perform the actual login. An AuthenticationException
			// will be thrown if the username is unrecognised or the
			// password is incorrect.
			SecurityUtils.subject.login(authToken)
			def userInstance = User.findByUsername(params.username)
			userInstance?.lastLoginDate = new Date()
			userInstance.save(flush:true)
			session.currentUser = userInstance
			log.info "Redirecting to '${targetUri}'."
			redirect(controller:"dashboard")
		}
		catch (AuthenticationException ex){
			// Authentication failed, so display the appropriate message
			// on the login page.
			log.info "Authentication failure for user '${params.username}'."
			flash.message = message(code: "login.failed")

			// Keep the username and "remember me" setting so that the
			// user doesn't have to enter them again.
			def m = [ username: params.username ]
			if (params.rememberMe) {
				m["rememberMe"] = true
			}

			// Remember the target URI too.
			if (params.targetUri) {
				m["targetUri"] = params.targetUri
			}

			// Now redirect back to the login page.
			redirect(controller: "index", params: m)
		}
	}

	def signOut = {
		// Log the user out of the application.
		def principal = SecurityUtils.subject?.principal
		SecurityUtils.subject?.logout()
		// For now, redirect back to the home page.
		if (ConfigUtils.getCasEnable() && ConfigUtils.isFromCas(principal)) {
			redirect(uri:ConfigUtils.getLogoutUrl())
		}else {
			redirect(uri: "/")
		}
		ConfigUtils.removePrincipal(principal)
	}
	
	def unauthorized = {
		render "You do not have permission to access this page."
	}
}

grails-app/views/layouts/_middleNavigation.gsp
<div id="content-header">
	<div id="breadcrumb">
		<g:link action="index" controller="dashboard" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Dashboard</g:link>
		<g:if test="${controllerName.equals('tax')}">
			<a href="#">Item Management</a>
			<a href="#" class="current">Tax</a>
		</g:if>
		<g:elseif test="${controllerName.equals('measurement')}">
			<a href="#">Item Management</a>
			<a href="#" class="current">Measurement</a>
		</g:elseif>
		<g:elseif test="${controllerName.equals('item')}">
			<a href="#">Item Management</a>
			<a href="#" class="current">Item</a>
		</g:elseif>
		<g:elseif test="${controllerName.equals('customer')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Customer</a>
				<a href="#" class="current">Create</a>
			</g:if>
			<g:elseif test="${actionName.equals('edit') }">
				<a href="#">Customer</a>
				<a href="#" class="current">Edit</a>
			</g:elseif>
			<g:else>
				<a href="#" class="current">Customer</a>
			</g:else>
		</g:elseif>
		<g:elseif test="${controllerName.equals('estimate')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Sales Management</a>
				<a href="#">Estimate</a>
				<a href="#" class="current">Create</a>
			</g:if>
			<g:elseif test="${actionName.equals('edit') }">
				<a href="#">Sales Management</a>
				<a href="#">Estimate</a>
				<a href="#" class="current">Edit</a>
			</g:elseif>
			<g:elseif test="${actionName.equals('estimateDetails') }">
				<a href="#">Sales Management</a>
				<a href="#">Estimate</a>
				<a href="#" class="current">Details</a>
			</g:elseif>
			<g:else>
				<a href="#">Sales Management</a>
				<a href="#" class="current">Estimate</a>
			</g:else>
		</g:elseif>
		<g:elseif test="${controllerName.equals('invoice')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Sales Management</a>
				<a href="#">Invoice</a>
				<a href="#" class="current">Create</a>
			</g:if>
			<g:elseif test="${actionName.equals('edit') }">
				<a href="#">Sales Management</a>
				<a href="#">Invoice</a>
				<a href="#" class="current">Edit</a>
			</g:elseif>
			<g:elseif test="${actionName.equals('invoiceDetails') }">
				<a href="#">Sales Management</a>
				<a href="#">Invoice</a>
				<a href="#" class="current">Details</a>
			</g:elseif>
			<g:else>
				<a href="#">Sales Management</a>
				<a href="#" class="current">Invoice</a>
			</g:else>
		</g:elseif>
		<g:elseif test="${controllerName.equals('receivedPayment')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Sales Management</a>
				<a href="#">Received Payment</a>
				<a href="#" class="current">Create</a>
			</g:if>
			<g:elseif test="${actionName.equals('edit') }">
				<a href="#">Sales Management</a>
				<a href="#">Received Payment</a>
				<a href="#" class="current">Edit</a>
			</g:elseif>
			<g:elseif test="${actionName.equals('received') }">
				<a href="#">Sales Management</a>
				<a href="#">Invoice</a>
				<a href="#">Received Payment</a>
				<a href="#" class="current">Create</a>
			</g:elseif>
			<g:else>
				<a href="#">Sales Management</a>
				<a href="#" class="current">Received Payment</a>
			</g:else>
		</g:elseif>
		<g:elseif test="${controllerName.equals('creditNote')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Sales Management</a>
				<a href="#">Credit Note</a>
				<a href="#" class="current">Create</a>
			</g:if>
			<g:elseif test="${actionName.equals('edit') }">
				<a href="#">Sales Management</a>
				<a href="#">Credit Note</a>
				<a href="#" class="current">Edit</a>
			</g:elseif>
			<g:elseif test="${actionName.equals('creditNoteDetails') }">
				<a href="#">Sales Management</a>
				<a href="#">Credit Note</a>
				<a href="#" class="current">Details</a>
			</g:elseif>
			<g:else>
				<a href="#">Sales Management</a>
				<a href="#" class="current">Credit Note</a>
			</g:else>
		</g:elseif>
		<g:elseif test="${controllerName.equals('refund')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Credit Note</a>
				<a href="#">Refund</a>
				<a href="#" class="current">Create</a>
			</g:if>
		</g:elseif>
		<g:elseif test="${controllerName.equals('applyCredit')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">Credit Note</a>
				<a href="#">Apply Credit</a>
				<a href="#" class="current">Create</a>
			</g:if>
		</g:elseif>
		<g:elseif test="${controllerName.equals('profile')}">
			<g:if test="${actionName.equals('edit') }">
				<a href="#">Profile</a>
				<a href="#" class="current">Edit</a>
			</g:if>
		</g:elseif>
		<g:elseif test="${controllerName.equals('user')}">
			<g:if test="${actionName.equals('create') }">
				<a href="#">User</a>
				<a href="#" class="current">Create</a>
			</g:if>
			<g:elseif test="${actionName.equals('edit') }">
				<a href="#">User</a>
				<a href="#" class="current">Edit</a>
			</g:elseif>
			<g:else>
				<a href="#" class="current">User</a>
			</g:else>
		</g:elseif>
	</div>
</div>

grails-app/views/layouts/_topNavigation.gsp
<div id="sidebar">
			<a href="#" class="visible-phone"><i class="icon icon-th-list"></i> Validation</a>
			<ul>
    <li ><g:link controller="dashboard"><i class="icon icon-home"></i> <span>Dashboard</span></g:link></li>
     <li class="submenu"> <a href="#"><i class="icon icon-file"></i> <span>Item</span></a>
      <ul>
        <li><g:link controller="tax" action="create">Tax</g:link></li>
        <%--<li><g:link controller="taxType" action="create">Tax Type</g:link></li>
      --%>
      <li><g:link controller="measurement" action="create">Measurement</g:link></li>
        <li><g:link controller="item" action="create">Item</g:link></li>
      </ul>
    </li>
    <li> <g:link controller="customer" action="search"><img src="${resource(dir: 'img', file: 'customer.png')}"/>  <span>Customer</span></g:link></li>
    <li class="submenu"> <a href="#"><i class="icon icon-signal"></i> <span>Sales</span></a>
    	<ul>
    		 <li> <g:link controller="estimate" action="search"> Estimate</g:link> </li>
		    <li> <g:link controller="invoice" action="search"> Invoice</g:link> </li>
		    <li> <g:link controller="receivedPayment" action="search">Received Payment</g:link> </li>
		    <li> <g:link controller="creditNote" action="search">Credit Note</g:link> </li>
		  </ul>
	</li>	    
		    <li> <g:link controller="report" action="index" params="[type:'invoice']"><i class="icon icon-book"></i> <span>Reports</span></g:link> </li>
    <li class="submenu"> <a href="#"><i class="icon  icon-search"></i> <span>Search</span></a>
      <ul>
      	<li><g:link controller="search" action="searchInvoice">Invoice</g:link></li>
        <li><g:link controller="search" action="searchCreditNote" >Credit Note</g:link></li>
      </ul>
    </li>
    <shiro:hasPermission permission="user:*">
    	<li> <g:link controller="user" action="search"><i class="icon icon-user"></i> <span>User</span></g:link> </li>
    </shiro:hasPermission>
    <li style="float: right"><span>Welcome <shiro:principal/> </span></li>
</div>

grails-app/views/layouts/form.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="${resource(dir: 'css', file: 'bootstrap.min.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'bootstrap-responsive.min.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'select2.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'uniform.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'billastick-style.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'billastick-media.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'jquery-ui.css')}" rel="stylesheet" type="text/css" />
		
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery-1.9.1.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery.min.js')}'></script>
  		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery-ui.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'bootstrap.min.js')}'></script>
		<script type='text/javascript' src='${resource(dir: 'js', file: 'jquery.uniform.js')}'></script> 
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'select2.min.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery.validate.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'billastick.form_common.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'common.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery.blockUI.js')}'></script>
				 
		 	
		  <script type="text/javascript">
			   function showSpinner(obj){
			        $('#' + obj).html("<img src='${resource(dir: 'img', file: 'spinner.gif')}' style=\'display: block; margin: 0 auto\'>")
			   }

			   $(document).ready(function(){
				   
				   //$('select').select2();
					//$('input[type=checkbox],input[type=radio],input[type=file]').uniform();
					
					/*$('select').select2();*/
				    //$('.datepicker').datepicker();
					$( ".uptoTodayDatepicker" ).datepicker({
						maxDate: '0',
						dateFormat : 'dd/mm/yy',
						 showOn: "button",
						 buttonImage: "${resource(dir: 'images', file: 'calendar.png')}",
						 buttonImageOnly: true,
						 changeMonth: true,
						 changeYear: true,
					});
					
					$( ".datepicker" ).datepicker({
						minDate : '0',
						dateFormat : 'dd/mm/yy',
						showOn: "button",
						 buttonImage: "${resource(dir: 'images', file: 'calendar.png')}",
						 buttonImageOnly: true,
						 changeMonth: true,
						 changeYear: true,
					});

					$( ".allDayDatepicker" ).datepicker({
						dateFormat : 'dd/mm/yy',
						showOn: "button",
						 buttonImage: "${resource(dir: 'images', file: 'calendar.png')}",
						 buttonImageOnly: true,
						 changeMonth: true,
						 changeYear: true,
					});
					
				});
			</script>

		<g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
		<!--Header-part-->
		<div id="header">
		  <h1></h1>
		</div>
		<!--close-Header-part-->
		
		<!--top-Header-messaages-->
		<div class="btn-group rightzero"> <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a> <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i></a> <a class="top_message tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a> <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a> </div>
		<!--close-top-Header-messaages-->  
		
		
		
		<!--top-Header-menu-->
		<div id="user-nav" class="navbar navbar-inverse"><ul class="nav">
		    <li class="" ><g:link title="Profile" action="edit" controller="profile" id="${session?.currentUser?.id }"><i class="icon icon-user"></i> <span class="text">Profile</span></g:link></li>
		    <%--<li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
		    --%><li class=""><g:link title="Logout" action="signOut" controller="auth"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></g:link></li>
		  </ul>
		</div>
		<!--close-top-Header-menu-->
		
		<!-- top-navigation-menu -->
			<g:render template="/layouts/topNavigation"></g:render>
		<!-- close top-navigation-menu -->
		
		<div id="content">
			<g:render template="/layouts/middleNavigation"></g:render>
			<g:layoutBody/>
		</div>
		
		<div class="row-fluid">
	      <div id="footer" class="span12"> Copyright &copy; 2013 Billastick. All rights reserved</div>
	    </div>
		
		
		
	</body>
</html>

grails-app/views/layouts/login.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="${resource(dir: 'css', file: 'bootstrap.min.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'bootstrap-responsive.min.css')}" rel="stylesheet" type="text/css" />
		<link href="${resource(dir: 'css', file: 'billastick-login.css')}" rel="stylesheet" type="text/css" />
		
		
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery.min.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'bootstrap.min.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'billastick.login.js')}'></script>
		 <script type='text/javascript' src='${resource(dir: 'js', file: 'jquery.validate.js')}'></script>
		<g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
	
		<%--<div id="logo">
            <img src="${resource(dir: 'img', file: 'login-logo.png')}" alt="" />
        </div>
		
		--%>
		<br><br><br><br><br><br><br><br>
		<div id="loginbox">
			<g:layoutBody/>  
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="${resource(dir: 'css/bootstrap', file: 'bootstrap.min.css')}" rel="stylesheet" type="text/css" />
		<g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>