grails-app/controllers/com/billing/controller/ReportController.groovy
package com.billing.controller

class ReportController {

	def reportService
	def index(){
		if(params?.type.equals("invoice")){
			[templateName : 'reportInvoiceDetailForm', params : params]
		}else if(params?.type.equals("payment")){
			[templateName : 'reportInvoicePaymentTypeDetailForm', params : params]
		}else if(params?.type.equals("invoice")){
			[templateName : 'reportInvoiceDetailsForm', params : params]
		}else{
			[templateName : 'reportInvoiceDetailForm', params : params]
		}
	}
	
	def invoiceReportByType(){
		reportService.generateInvoiceListReportByInvoiceType(params)
	}
	
	def invoiceReportByPaymentType(){
		reportService.generateInvoiceListReportByPaymentType(params)
	}
	
	def renderPage(){
		if(params?.type.equals("invoice")){
		}else if(params?.type.equals("payment")){
		}else if(params?.type.equals("invoice")){
		}
	}
	
	
}

grails-app/views/report/_reportInvoiceDetailForm.gsp
<%@page import="com.billing.utility.ReportFormat"%>
<%@page import="com.billing.utility.InvoiceType"%>
<g:form class="form-horizontal" name="reportOptionForm" action="invoiceReportByType" controller="report">
<div class="chat-message well" style="text-align: center;width: 90%;margin-left: 10%">
     <h6>By Invoice Type</h6>
</div>
<div class="chat-content panel-left2">
	<label class="control-label"><g:message
			code="tax.taxName.label" default="From" /></label>
	<div class="controls">
		<input type="text" class="allDayDatepicker" id="fromDate"
			name="fromDate" size="10" value="${params?.fromDate}" />
	</div>
	<label class="control-label"><g:message
			code="tax.taxName.label" default="To" /></label>
	<div class="controls">
		<input type="text" class="allDayDatepicker" id="toDate" name="toDate"
			size="10" value="${params?.toDate}" />
	</div>

	<label class="control-label"><g:message
			code="tax.taxName.label" default="Invoice Type" /></label>
	<div class="controls">
		<g:select name="invoiceType" name="invoiceType"
			from="${InvoiceType.list()}" noSelection="['':'All']" value="" />
	</div>
	
	 <div class="control-group">
		<label class="control-label">Report Format</label>
		<div class="controls">
			<label><g:radio name="reportFormat" value="${ReportFormat.Pdf}" checked="${invoiceInstance?.invoiceType == InvoiceType.Retail ? 'true' : 'false' }" /> ${ReportFormat.Pdf}</label>
			<label><g:radio name="reportFormat" value="${ReportFormat.Excel}" checked="${invoiceInstance?.invoiceType == InvoiceType.Tax}"  /> ${ReportFormat.Excel}</label>
		</div>
	</div>
	
	<div style="margin-left: 20%">
     	<g:submitButton name="invoiceReportByType" class="btn btn-success" value="${message(code: 'default.button.save.label', default: 'Generate')}" />
    </div>  
</div>
</g:form>

grails-app/views/report/_reportInvoicePaymentTypeDetailForm.gsp
<%@page import="com.billing.utility.PaymentType"%>
<%@page import="com.billing.utility.ReportFormat"%>
<%@page import="com.billing.utility.InvoiceType"%>
<g:form class="form-horizontal" name="reportOptionForm" action="invoiceReportByPaymentType" controller="report">
<div class="chat-message well" style="text-align: center;width: 90%;margin-left: 10%">
     <h6>By Payment Type</h6>
</div>
<div class="chat-content panel-left2">
	<label class="control-label"><g:message
			code="tax.taxName.label" default="From" /></label>
	<div class="controls">
		<input type="text" class="allDayDatepicker" id="fromDate"
			name="fromDate" size="10" value="${params?.fromDate}" />
	</div>
	<label class="control-label"><g:message
			code="tax.taxName.label" default="To" /></label>
	<div class="controls">
		<input type="text" class="allDayDatepicker" id="toDate" name="toDate"
			size="10" value="${params?.toDate}" />
	</div>

	<label class="control-label"><g:message
			code="tax.taxName.label" default="Payment Type" /></label>
	<div class="controls">
		<g:select name="paymentType" name="paymentType"
			from="${PaymentType.list()}" noSelection="['':'All']" value="" />
	</div>
	
	 <div class="control-group">
		<label class="control-label">Report Format</label>
		<div class="controls">
			<label><g:radio name="reportFormat" value="${ReportFormat.Pdf}"  checked="checked"/> ${ReportFormat.Pdf}</label>
			<label><g:radio name="reportFormat" value="${ReportFormat.Excel}"  /> ${ReportFormat.Excel}</label>
		</div>
	</div>
	
	<div style="margin-left: 20%">
     	<g:submitButton name="invoiceReportByType" class="btn btn-success" value="${message(code: 'default.button.save.label', default: 'Generate')}" />
    </div>  
</div>
</g:form>

grails-app/views/report/index.gsp
<%@page import="com.billing.utility.InvoiceType"%>
<%@page import="org.hibernate.event.def.OnLockVisitor"%>
<%@ page import="com.billing.domain.Tax" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="form">
		<g:set var="entityName" value="${message(code: 'tax.label', default: 'Tax')}" />
		<title>Credit Note</title>
	</head>
	<body>
	<!-- End of content-header -->
			
               <div class="container-fluid">
				<div class="row-fluid">
					<div class="span10">
			            <div class="widget-box widget-chat">
			              <div class="widget-title"> <span class="icon"> <i class="icon-file"></i> </span>
			                <h5>Report Option</h5>
			              </div>
			              <div class="widget-content nopadding">
			                <div class="chat-users panel-right2">
			                  <div class="panel-title">
			                    <h5>Report</h5>
			                  </div>
			                  <div class="panel-content nopadding">
			                    <ul class="contact-list">
			                      <li id="user-Sunil" class="online ${params?.type.equals('invoice') ? 'new' : ''}"><g:link action="index" params="[type:'invoice']"><span>Tax/Retails Invoices</span></g:link></li>
			                      <li id="user-Laukik" class="online ${params?.type.equals('payment') ? 'new' : ''}"><g:link action="index" params="[type:'payment']" ><span>Cash/Credit Invoices</span></g:link></li>
			                      <%--<li id="user-vijay" class="online ${params?.type.equals('customer') ? 'new' : ''}"><g:link action="index" params="[type:'customer']"> <span>By Customer</span></g:link></li>
			                    --%></ul>
			                  </div>
			                </div>
				            <div id="reportForm">
				                	<g:render template="${templateName ?: 'reportInvoiceDetailForm'}"></g:render>
				            </div>
			              </div>
			            </div>
			          </div>
			</div><!-- End of row-fluid -->
	</div><!-- End of container-fluid -->
	</body>
</html>