grails-app/domain/com/billing/domain/CreditNote.groovy
package com.billing.domain

import com.billing.utility.InvoiceStatus
import com.billing.utility.InvoiceType;
import com.billing.utility.PaymentType;


class CreditNote {

	Integer creditNoteNumber
	InvoiceStatus creditNoteStatus = InvoiceStatus.Open
	BigDecimal subTotal
	BigDecimal netTotal
	BigDecimal balanceDue = 0.0
	Integer refNumber
	Date lastUpdated
	Date dateCreated
	Date creditNoteDate
	Boolean status = Boolean.TRUE
	String customerNotes
	String termsConditions
	List invoiceDetails
	List taxTransactionDetails
	Boolean isPrinted = Boolean.FALSE
	
    static constraints = {
		creditNoteStatus nullable:true, blank : true
		refNumber nullable:true, blank : true
		creditNoteDate nullable:true, blank : true
		subTotal nullable:true, blank : true
		netTotal nullable:true, blank : true
		creditNoteNumber nullable:true, blank : true
		customerNotes nullable:true, blank : true
		termsConditions nullable:true, blank : true
		invoiceDetails nullable:true, blank : true
		balanceDue nullable:true, blank : true
		invoice nullable:true, blank : true
    }
	
	static belongsTo = [customer : Customer, user : User, invoice : Invoice]
	static hasMany = [invoiceDetails : InvoiceDetail, taxTransactionDetails : TaxTransactionDetails]
	
	static mapping = {
		invoiceDetails lazy: false
		taxTransactionDetails lazy: false
		invoiceDetails cascade: "all-delete-orphan"
		taxTransactionDetails cascade: "all-delete-orphan"
	 }
}

grails-app/controllers/com/billing/controller/CreditNoteController.groovy
package com.billing.controller

import grails.converters.JSON

import org.apache.commons.lang.math.NumberUtils
import org.springframework.dao.DataIntegrityViolationException

import com.billing.domain.CreditNote
import com.billing.domain.Invoice
import com.billing.domain.InvoiceDetail
import com.billing.domain.Item
import com.billing.domain.Tax
import com.billing.domain.TaxTransactionDetails
import com.billing.domain.TaxType
import com.billing.exception.BillingException

class CreditNoteController {

	static allowedMethods = [save: "POST", update: "POST", autocompleteItem : "POST"]
	def customerService
	def taxService
	def itemService
	def baseService
	def creditNoteService
	def reportService
	def refundService
	def applyCreditService

	def index() {
		redirect(action: "search", params: params)
	}

	def search(Integer max){
		params.max = Math.min(max ?: 10, 100)
		def creditNoteInstanceList = creditNoteService.getCreditNoteList(params) //customerService.getCustomerList(params)
		def creditNoteInstanceListTotal = creditNoteService.getCreditNoteListSize(params) //customerService.getCustomerListSize(params)
		if(request.xhr){
			render(template : 'dataList',  model : [creditNoteInstanceList :creditNoteInstanceList , creditNoteInstanceListTotal : creditNoteInstanceListTotal])
		}else{
			[creditNoteInstanceList :creditNoteInstanceList , creditNoteInstanceListTotal : creditNoteInstanceListTotal]
		}
	}

	def view(){
		def creditNoteInstance = CreditNote.read(params?.id)
		[creditNoteInstance : creditNoteInstance]
	}

	def create() {
		def taxList = taxService.getAllTaxList();
		def creditNoteNumber = creditNoteService.getCreditNoteNumber()
		def customerList = customerService.getCustomerListByUser()
		def itemList = itemService.getAllItemByUser()
		def invoiceInstance = Invoice.read(params?.id)
		[invoiceInstance : invoiceInstance, creditNoteInstance: new CreditNote(params), taxList : taxList,  creditNoteNumber : creditNoteNumber, customerList : customerList, itemList : itemList]
	}

	def save() {

		def creditNoteInstance = new CreditNote()
		creditNoteInstance.creditNoteNumber = NumberUtils.toInt(params?.creditNoteNumber)
		def customerInstance =  customerService.getCustomerById(params?.customerId)
		def invoiceInstance = Invoice.read(params?.invoiceId)
		
		creditNoteInstance.invoice = invoiceInstance
		creditNoteInstance.customer = customerInstance
		creditNoteInstance.user = baseService.getLoggedInUser()
		creditNoteInstance.subTotal = params?.hiddenSubTotal as BigDecimal
		creditNoteInstance.netTotal = params?.hiddenNetTotal as BigDecimal
		creditNoteInstance.balanceDue = params?.hiddenNetTotal as BigDecimal
		if(params?.creditNoteDate){
			creditNoteInstance.creditNoteDate = java.util.Date.parse("dd/MM/yyyy", params?.creditNoteDate)
		}
		
		if(params?.refNumber){
			creditNoteInstance.refNumber = NumberUtils.toInt(params?.refNumber)
		}

		creditNoteInstance.customerNotes = params?.customerNotes
		
		if(creditNoteInstance.validate()){
			try{
				creditNoteService.saveCreditNote(creditNoteInstance ,params)
				flash.message = message(code: 'default.created.message')
			}catch(BillingException be){
				be.printStackTrace()
				flash.errorMessage = be.getMessage()
			}catch(Exception e){
				e.printStackTrace()
			}
		}else{
			def customerList = customerService.getCustomerListByUser()
			def taxList = taxService.getAllTaxList();
			def dbItemList = itemService.getAllItemByUser()
			render(view: "create", model: [invoiceInstance : invoiceInstance, creditNoteInstance : creditNoteInstance, taxList : taxList, params : params, customerList : customerList, itemList : dbItemList])
			return
		}

		redirect(action: "search", controller :"invoice")
	}


	def edit(Long id) {
		def creditNoteInstance = CreditNote.read(id)
		def invoiceInstance = Invoice.read(creditNoteInstance?.invoice?.id)
		if (!creditNoteInstance) {
			flash.message = message(code: 'default.not.found.message')
			redirect(action: "search")
			return
		}
		def taxList = taxService.getAllTaxList();
		def customerList = customerService.getCustomerListByUser()
		def dbItemList = itemService.getAllItemByUser()
		def totalRefundedAmount = creditNoteService.getTotalRefundedAmount(creditNoteInstance)
		def totalCreditUsedAmount = creditNoteService.getTotalCreditUsedAmount(creditNoteInstance)
		[invoiceInstance : invoiceInstance , creditNoteInstance: creditNoteInstance, taxList : taxList, customerList : customerList, itemList : dbItemList , totalRefundedAmount : totalRefundedAmount, totalCreditUsedAmount : totalCreditUsedAmount]
	}

	def update(Long id, Long version) {
		def creditNoteInstance = CreditNote.read(id)
		def customerInstance =  customerService.getCustomerById(params?.customerId)
		creditNoteInstance.user = baseService.getLoggedInUser()
		creditNoteInstance.creditNoteNumber = NumberUtils.toInt(params?.creditNoteNumber)
		creditNoteInstance.customer = customerInstance

		creditNoteInstance.subTotal = params?.hiddenSubTotal as BigDecimal
		creditNoteInstance.netTotal = params?.hiddenNetTotal as BigDecimal
		creditNoteInstance.balanceDue = params?.hiddenNetTotal as BigDecimal

		if(params?.creditNoteDate){
			params.creditNoteDate = java.util.Date.parse("dd/MM/yyyy", params?.creditNoteDate)
		}
		if(params?.refNumber){
			creditNoteInstance.refNumber = NumberUtils.toInt(params?.refNumber)
		}

		if (!creditNoteInstance) {
			flash.message = message(code: 'default.not.found.message')
			redirect(action: "search")
			return
		}

		creditNoteInstance.invoiceDetails.clear()
		creditNoteInstance.taxTransactionDetails.clear()

		if (version != null) {
			if (creditNoteInstance.version > version) {
				creditNoteInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
						[
							message(code: 'customer.label', default: 'Customer')] as Object[],
						"Another user has updated this Customer while you were editing")
				def taxList = taxService.getAllTaxList();
				def customerList = customerService.getCustomerListByUser()
				def dbItemList = itemService.getAllItemByUser()
				render(view: "edit", model: [creditNoteInstance: creditNoteInstance, taxList : taxList, itemList : dbItemList, customerList : customerList])
				return
			}
		}

		creditNoteInstance.properties = params

		if (!creditNoteInstance.validate(flush: true)) {
			def taxList = taxService.getAllTaxList();
			def customerList = customerService.getCustomerListByUser()
			def dbItemList = itemService.getAllItemByUser()
			render(view: "edit", model: [creditNoteInstance: creditNoteInstance, taxList : taxList, itemList : dbItemList, customerList : customerList])
			return
		}else{
			creditNoteService.saveCreditNote(creditNoteInstance, params)
		}

		flash.message = message(code: 'default.updated.message')
		redirect(action: "edit", id: creditNoteInstance.id)
	}

	def delete(Long id) {
		def creditNoteInstance = CreditNote.read(id)
		if (!creditNoteInstance) {
			flash.message = message(code: 'default.not.found.message')
			redirect(action: "search", controller :"invoice")
			return
		}

		try {
			creditNoteService.deleteCreditNote(creditNoteInstance)
			//invoiceInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message')
			redirect(action: "search", controller :"invoice")
		}catch(BillingException be){
			flash.infoMessage = be.getMessage()
			redirect(action: "search", controller :"invoice", id: id)
		}catch (DataIntegrityViolationException e) {
			flash.infoMessage = "Record can not be deleted, child reference is exsist."
			redirect(action: "search", controller :"invoice" , id: id)
		}
	}
	
	def details(){
		def creditNoteInstance = CreditNote.read(params?.id)
		[creditNoteInstance : creditNoteInstance]
	}

	
	def getItemDetails = {
		def itemInstance = Item.read(params?.id)
		def taxList = taxService.getAllTaxList();
		def itemMap = [:]
		def assignedItemTaxList = itemInstance?.tax*.id
		itemInstance?.tax?.eachWithIndex{taxInstance, i->
			i++
			itemMap.put('taxId' + i,taxInstance?.id?:"")
			itemMap.put('taxRate' + i,taxInstance?.taxRate?:0)
		}
		itemMap.put('itemRate', itemInstance?.rate)
		itemMap.put('taxList', taxList)
		itemMap.put('appliedTaxIdList', itemInstance?.tax?:"")
		itemMap.put('elementId', params?.elementId)
		render itemMap as JSON

	}

	def getTaxDetails = {
		def taxInstance = Tax.read(params?.id)
		def taxList = taxService.getAllTaxList();
		def taxMap = [:]
		taxMap.put('elementId', params?.elementId)
		taxMap.put('taxList', taxList)
		render taxMap as JSON

	}

	def printCreditNote(){
		reportService?.generateCreditNote(params)
		return
	}
	
	def creditNoteDetails(Integer max){
		params.max = Math.min(max ?: 10, 100)
		def creditNoteInstance = CreditNote.read(params?.id)
		def refundInstanceList = refundService.getAllRefundDetailsListByCreditNote(params, creditNoteInstance)
		def refundInstanceListTotal = refundService.getAllRefundDetailsListSizeByCreditNote(params, creditNoteInstance)
		if(request.xhr){
			render(template:"refundList", model : [refundInstanceList : refundInstanceList, refundInstanceListTotal : refundInstanceListTotal, invoicedCreditListTotal : 0, creditNoteInstance : creditNoteInstance])
		}else{
			[ creditNoteInstance : creditNoteInstance ,refundInstanceList : refundInstanceList, refundInstanceListTotal : refundInstanceListTotal, invoicedCreditListTotal : 0]
		}
	}
	
	
	def getInvoicedCreditListByCreditNote(Integer max){
		params.max = Math.min(max ?: 10, 100)
		def creditNoteInstance = CreditNote.read(params?.id)
		def invoicedCreditList = applyCreditService.getAllInvoicedCreditDetailsListByCreditNote(params, creditNoteInstance)
		def invoicedCreditListTotal = applyCreditService.getAllInvoicedCreditDetailsListSizeByCreditNote(params, creditNoteInstance)
		render (template : "invoiceCreditList", model : [invoicedCreditList : invoicedCreditList, invoicedCreditListTotal : invoicedCreditListTotal])
	}
}

grails-app/views/creditNote/_creditNote.gsp
<div class="content">

	<div class="page-header">
		<div class="icon">
			<span class="ico-dollar"></span>
		</div>
		<h3>
			Credit Note # ${creditNoteInstance?.creditNoteNumber} 
		</h3>
	</div>

	<div class="row-fluid">
		<div class="span12">

			<div class="block">
				<div class="data invoice">

					<div class="row-fluid">
						<div class="span3">
							<address>
								<strong>${creditNoteInstance?.user?.displayName}</strong>
								<g:if test="${creditNoteInstance?.user?.address1}">
								<br> ${creditNoteInstance?.user?.address1}
								</g:if>
								<g:if test="${creditNoteInstance?.user?.address2}">
								<br> ${creditNoteInstance?.user?.address2}
								</g:if>
								<g:if test="${creditNoteInstance?.user?.city}">
								<br>${creditNoteInstance?.user?.city}
								</g:if>
								<g:if test="${creditNoteInstance?.user?.mobileNumber}">
								<br>Mobile:	${creditNoteInstance?.user?.mobileNumber}
								</g:if>
							</address>
						</div>
						<div class="span3">
							<address>
								<strong>${creditNoteInstance?.customer?.customerName}</strong>
								<g:if test="${creditNoteInstance?.customer?.address1}">
								<br> ${creditNoteInstance?.customer?.address1}
								</g:if>
								<g:if test="${creditNoteInstance?.customer?.address2}">
								<br> ${creditNoteInstance?.customer?.address2} 
								</g:if>
								<g:if test="${creditNoteInstance?.customer?.city}">
								<br>${creditNoteInstance?.customer?.city}
								</g:if>
								<g:if test="${creditNoteInstance?.customer?.mobileNumber}">
								<br>Phone :  ${creditNoteInstance?.customer?.mobileNumber}
								</g:if>
							</address>
						</div>
						<div class="span3"></div>
						<div class="span3">
								<strong>Credit Note Date:</strong> <g:formatDate format='dd/MM/yyyy' date='${creditNoteInstance?.creditNoteDate}'/><br>
							<div class="highlight">
								<strong>Credit Note Amount:</strong> ${creditNoteInstance?.netTotal}  <em>INR</em>
							</div>
						</div>
					</div>

					<h4>Description</h4>
					<table class="table" width="100%">
						<thead>
							<tr>
								<th width="60%" style="text-align: left">Description</th>
								<th width="10%" style="text-align: right">Price</th>
								<th width="10%" style="text-align: right">Quantity</th>
								<th width="10%" style="text-align: right">Discount</th>
								<th width="10%" style="text-align: right">Tax1</th>
								<th width="10%" style="text-align: right">Tax2</th>
								<th width="10%" style="text-align: right">Tax3</th>
								<th width="10%" style="text-align: right">Total</th>
							</tr>
						</thead>
						<tbody>
						<g:each in="${creditNoteInstance?.invoiceDetails}" var="detailsInstance">
							<tr>
								<td>${detailsInstance?.item?.itemName }</td>
								<td style="text-align: right">${detailsInstance?.rate}</td>
								<td style="text-align: right">${detailsInstance?.quantity}</td>
								<td style="text-align: right">${detailsInstance?.discountRate}%</td>
								<td style="text-align: right">${detailsInstance?.tax1 == null ? 'N/A' : detailsInstance?.tax1?.taxName + '@'+ detailsInstance?.tax1?.taxRate + '%'}</td>
								<td style="text-align: right">${detailsInstance?.tax2 == null ? 'N/A' : detailsInstance?.tax2?.taxName + '@'+ detailsInstance?.tax2?.taxRate + '%'}</td>
								<td style="text-align: right">${detailsInstance?.tax3 == null ? 'N/A' : detailsInstance?.tax3?.taxName + '@'+ detailsInstance?.tax3?.taxRate + '%'}</td>
								<td style="text-align: right">${detailsInstance?.total }</td>
							</tr>
						</g:each>	
						</tbody>
					</table>

					<div class="row-fluid">
						<div class="span9"></div>
						<div class="span3">
							<table class="table" width="100%">
								<tr ><td><span><b>Sub Total:</b></span></td><td style="text-align: right">${creditNoteInstance?.subTotal}</td></tr>
								<g:each in="${creditNoteInstance?.taxTransactionDetails}" var="taxTransactionInstance">
									<tr ><td><span>${taxTransactionInstance?.tax?.taxName + '@'+ taxTransactionInstance?.tax?.taxRate + '%'}:</span></td><td style="text-align: right">${taxTransactionInstance?.taxAmount}</td></tr>	
								</g:each>
								<tr class="highlight"><td><span><b>Net Total:</b></span></td><td style="text-align: right"> ${creditNoteInstance?.netTotal}</td></tr>
							</table>	
						</div>
					</div>

				</div>

			</div>

		</div>
	</div>

</div>

grails-app/views/creditNote/_dataList.gsp
<%@ page import="com.billing.utility.InvoiceStatus" %>
<table class="table table-bordered data-table">
	<thead>
		<tr>
			<util:remoteSortableColumn action="search" onLoading="showSpinner(\'creditNoteListDiv\')" property="creditNoteNumber" update="creditNoteListDiv" title="Credit Note#" defaultOrder="asc" params="[max:params?.max ?: 10, searchText : params?.searchText?:'']"/>
			<th style="text-align: left">Customer Name</th>
			<th style="text-align: right">Invoice#</th>
			<th style="text-align: right">Amount</th>
			<th style="text-align: right">Credit Date</th>
			<th style="text-align: right">Actions</th>
		</tr>
	</thead>
	<tbody>
		<g:if test="${creditNoteInstanceList?.size() > 0 }">
				<g:each in="${creditNoteInstanceList}" var="creditNoteInstance" status="i">
					<tr class="gradeX">
						<td width="10%" style="text-align: center">${creditNoteInstance?.creditNoteNumber }</td>
						<td>${creditNoteInstance?.customer.customerName }</td>
						<td style="text-align: right" width="10%"><g:link id="${creditNoteInstance?.invoice?.id}" action="invoiceDetails" controller="invoice">${creditNoteInstance?.invoice?.invoiceNumber}</g:link></td>
						<td style="text-align: right" width="10%">${creditNoteInstance?.netTotal}</td>
						<td style="text-align: right" width="10%"><g:formatDate format='dd/MM/yyyy' date='${creditNoteInstance?.creditNoteDate}'/></td>
						<td width="5%">
							 <div class="btn-group">
									  <button class="btn btn-primary">Action</button>
									  <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
									  <ul class="dropdown-menu">
									  	<li><g:link action="edit" controller="creditNote" id="${creditNoteInstance?.id}"><i class="icon-pencil"></i>&nbsp;Edit</g:link></li>
										<li><a href="#myAlert${i}" data-toggle="modal"><i class="icon-trash"></i>&nbsp;Delete</a></li>
										<li><g:link id="${creditNoteInstance?.id}" controller="creditNote" action="details"><i class="icon-th-list"></i>&nbsp;Details</g:link></li>
										<li><g:link id="${creditNoteInstance?.id}" controller="creditNote" action="printCreditNote"><i class="icon-print"></i>&nbsp;Print</g:link></li>
									  </ul>
								</div>
                                <div id="myAlert${i}" class="modal hide">
					              <div class="modal-header">
					                <button data-dismiss="modal" class="close" type="button">×</button>
					                <h3>Delete</h3>
					              </div>
					              <div class="modal-body">
					                <p>Once you choose to delete, the details of the credit note will be removed from the system forever and you will not be able to retrieve it later. Are you sure about deleting this credit note?</p>
					              </div>
					              <div class="modal-footer"> <g:link action="delete" id="${creditNoteInstance?.id}" class="btn btn-primary" href="#">Confirm</g:link> <a data-dismiss="modal" class="btn" href="#">Cancel</a> </div>
					            </div>
						</td>
					</tr>
				</g:each>
		</g:if>	
		<g:else>
			<tr class="gradeX">
				<td colspan="8" style="text-align: center">No record found</td>
			</tr>
		</g:else>		
	</tbody>
</table>
<div style="float:right" class="pagination">
<util:remotePaginate action="list" total="${creditNoteInstanceListTotal}" 
			update="creditNoteListDiv" max="${params?.max ?: 10 }" offset="${params?.offset }" params="[searchText : params?.searchText?:'']" onLoading="showSpinner(\'creditNoteListDiv\')"/>
</div>

grails-app/views/creditNote/_invoiceCreditList.gsp
<%@ page import="com.billing.utility.ReceivedPaymentStatus" %>
<table class="table table-bordered data-table" style="width: 50%">
	<thead>
		<tr>
			<util:remoteSortableColumn action="getInvoicedCreditListByCreditNote" onLoading="showSpinner(\'invoiceCreditListTab\')" property="dateCreated" update="invoiceCreditListTab" title="Invoice Date" defaultOrder="asc" params="[max:params?.max ?: 10, id : params?.id?:'']"/>
			<th style="text-align: right">Invoice #</th>
			<th style="text-align: right">Credits Applied</th>
			<th style="text-align: center">Actions</th>
		</tr>
	</thead>
	<tbody>
		<g:if test="${invoicedCreditList?.size() > 0 }">
				<g:each in="${invoicedCreditList}" var="appliedCreditInstance" status="i">
					<tr class="gradeX">
						<td width="10%" style="text-align: center"><g:formatDate format='dd/MM/yyyy' date='${appliedCreditInstance?.dateCreated }'/></td>
						<td style="text-align: right" width="10%">${appliedCreditInstance?.invoice?.invoiceNumber }</td>
						<td  width="10%" style="text-align: right">${appliedCreditInstance?.creditAmount}</td>
						<td width="1%" style="text-align: center">
								<a href="#myAlertCredit${i}" data-toggle="modal"><i class="icon-trash"></i>&nbsp;</a>
						</td>
						 <div id="myAlertCredit${i}" class="modal hide">
					              <div class="modal-header">
					                <button data-dismiss="modal" class="close" type="button">×</button>
					                <h3>Delete</h3>
					              </div>
					              <div class="modal-body">
					                <p>Are you sure you want to delete this record?</p>
					              </div>
					              <div class="modal-footer"> <g:link action="delete" controller="applyCredit" id="${appliedCreditInstance?.id}" class="btn btn-primary" href="#">Confirm</g:link> <a data-dismiss="modal" class="btn" href="#">Cancel</a> </div>
					            </div>
					</tr>
				</g:each>
		</g:if>	
		<g:else>
			<tr class="gradeX">
				<td colspan="4" style="text-align: center">No record found</td>
			</tr>
		</g:else>		
	</tbody>
</table>
<div style="float:right;margin-right: 50%" class="pagination">
<util:remotePaginate action="getInvoicedCreditListByCreditNote" total="${invoicedCreditListTotal}" 
			update="invoiceCreditListTab" max="${params?.max ?: 10 }" offset="${params?.offset }" params="[id:params?.id]" onLoading="showSpinner(\'invoiceCreditListTab\')"/>
</div>

grails-app/views/creditNote/_refundList.gsp
<%@ page import="com.billing.utility.ReceivedPaymentStatus" %>
<table class="table table-bordered data-table" style="width: 50%">
	<thead>
		<tr>
			<util:remoteSortableColumn action="creditNoteDetails" onLoading="showSpinner(\'refundListTab\')" property="dateCreated" update="refundListTab" title="Refund Date" defaultOrder="asc" params="[max:params?.max ?: 10, id : params?.id?:'']"/>
			<th style="text-align: right">Payment Method</th>
			<th style="text-align: right">Amount</th>
			<th style="text-align: center">Actions</th>
		</tr>
	</thead>
	<tbody>
		<g:if test="${refundInstanceList?.size() > 0 }">
				<g:each in="${refundInstanceList}" var="refundInstance" status="i">
					<tr class="gradeX">
						<td width="10%" style="text-align: center"><g:formatDate format='dd/MM/yyyy' date='${refundInstance?.refundDate }'/></td>
						<td style="text-align: right" width="10%">${refundInstance?.paymentMethod }</td>
						<td  width="10%" style="text-align: right">${refundInstance?.refundAmount}</td>
						<td width="1%" style="text-align: center">
							<a href="#myAlert${i}" data-toggle="modal"><i class="icon-trash" title="Delete"></i>&nbsp;</a>
						</td>
						 <div id="myAlert${i}" class="modal hide">
					              <div class="modal-header">
					                <button data-dismiss="modal" class="close" type="button">×</button>
					                <h3>Delete</h3>
					              </div>
					              <div class="modal-body">
					                <p>Are you sure you want to delete this record?</p>
					              </div>
					              <div class="modal-footer"> <g:link action="delete" controller="refund" id="${refundInstance?.id}" class="btn btn-primary" href="#">Confirm</g:link> <a data-dismiss="modal" class="btn" href="#">Cancel</a> </div>
					            </div>
					</tr>
				</g:each>
		</g:if>	
		<g:else>
			<tr class="gradeX">
				<td colspan="4" style="text-align: center">No record found</td>
			</tr>
		</g:else>		
	</tbody>
</table>
<div style="float:right;margin-right: 50%" class="pagination">
<util:remotePaginate action="creditNoteDetails" total="${refundInstanceListTotal}" 
			update="refundListTab" max="${params?.max ?: 10 }" offset="${params?.offset }" params="[id : params?.id?:'']" onLoading="showSpinner(\'refundListTab\')"/>
</div>

grails-app/views/creditNote/details.gsp
<%@page import="org.hibernate.event.def.OnLockVisitor"%>
<%@ page import="com.billing.domain.Tax" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="form">
		<g:set var="entityName" value="${message(code: 'tax.label', default: 'Tax')}" />
		<title>Credit Note Details</title>
	</head>
	<body>
	<!-- End of content-header -->
			
               <div class="container-fluid">
				<div class="row-fluid">
					<div class="span10">
					
						 <g:if test="${flash.infoMessage}">
							<div class="alert alert-info">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Info!</strong> ${flash.infoMessage}
			          		 </div>
			             </g:if>   
			              <g:if test="${flash.errorMessage}">
							<div class="alert alert-error">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Error!</strong> ${flash.errorMessage}
			          		 </div>
			             </g:if>   
				         <g:if test="${flash.message}">
							<div class="alert alert-success">
					          <button class="close" data-dismiss="alert">×</button>
					          <strong>Success!</strong> ${flash.message }
					         </div>
			              </g:if>
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="icon-align-justify"></i>									
								</span>
								<span class="icon" style="float:right"><g:link action="search" controller="creditNote" id="${creditNoteInstance?.id}"><i class="icon-arrow-left" title="Cancel"></i>&nbsp;</g:link></span>
								<span class="icon" style="float:right"><g:link action="printCreditNote" controller="creditNote" id="${creditNoteInstance?.id}"><i class="icon-print" title="Print"></i>&nbsp;</g:link></span>
								<span class="icon" style="float:right"><g:link action="edit" controller="creditNote" id="${creditNoteInstance?.id}"><i class="icon-pencil" title="Edit"></i>&nbsp;</g:link></span>
								<span class="icon" style="float:right">&nbsp;</span>
								<h5>Credit Note Details</h5>
							</div>
							<g:form class="form-horizontal">
								<g:render template="creditNote"></g:render>
							</g:form>
						</div><!-- End of widget-box -->	
						
					</div><!-- End of span6 -->
			</div><!-- End of row-fluid -->
	</div><!-- End of container-fluid -->
	</body>
</html>