grails-app/domain/com/billing/domain/Estimate.groovy
package com.billing.domain

import java.math.BigDecimal;
import java.util.Date;

import com.billing.utility.InvoiceStatus;
import com.billing.utility.InvoiceType;
import com.billing.utility.PaymentType;


class Estimate {

	Integer estNumber
	InvoiceStatus estimateStatus = InvoiceStatus.Open
	BigDecimal subTotal
	BigDecimal netTotal
	BigDecimal paymentMade = 0.0
	BigDecimal balanceDue = 0.0
	boolean isCashMemo = false
	Date lastUpdated
	Date dateCreated
	Boolean status = Boolean.TRUE
	String customerNotes
	String termsConditions
	List estimateDetails
	List estimateTaxTransactionDetails
	Date estimateDate
	Date expireDate
	
	PaymentType paymentType = PaymentType.Credit
	InvoiceType invoiceType = InvoiceType.Retail
	Boolean isPrinted = Boolean.FALSE
	BigDecimal totalBalanceDue = 0.0
	
	static constraints = {
		estimateStatus nullable:true, blank : true
		estNumber nullable:true, blank : true
		customerNotes nullable:true, blank : true
		termsConditions nullable:true, blank : true
		subTotal nullable:true, blank : true
		netTotal nullable:true, blank : true
		estimateDetails nullable:true, blank : true
		estimateDate nullable:false, blank : false
		expireDate nullable:true, blank : true
	}
	
	static belongsTo = [customer : Customer, user : User]
	static hasMany = [estimateDetails : InvoiceDetail, estimateTaxTransactionDetails : TaxTransactionDetails]
	static mapping = {
		estimateDetails lazy: false
		estimateDetails cascade: "all-delete-orphan"
		
		estimateTaxTransactionDetails lazy: false
		estimateTaxTransactionDetails cascade: "all-delete-orphan"
	 }
}

grails-app/controllers/com/billing/controller/EstimateController.groovy
package com.billing.controller

import grails.converters.JSON

import org.apache.commons.lang.math.NumberUtils
import org.springframework.dao.DataIntegrityViolationException

import com.billing.domain.Estimate
import com.billing.domain.InvoiceDetail
import com.billing.domain.Item
import com.billing.domain.TaxType

class EstimateController {

	static allowedMethods = [save: "POST", update: "POST", autocompleteItem : "POST"]
	def customerService
	def taxService
	def itemService
	def baseService
	def invoiceService
	def reportService
	
	def index() {
		redirect(action: "search", params: params)
	}

	def search(Integer max){
		params.max = Math.min(max ?: 10, 100)
		def estimateInstanceList = invoiceService.getEstimateList(params) //customerService.getCustomerList(params)
		def estimateInstanceListTotal = invoiceService.getEtimateListSize(params) //customerService.getCustomerListSize(params)
		if(request.xhr){
			render(template : 'dataList',  model : [estimateInstanceList :estimateInstanceList , estimateInstanceListTotal : estimateInstanceListTotal])
		}else{
			[estimateInstanceList :estimateInstanceList , estimateInstanceListTotal : estimateInstanceListTotal]
		}
	}

	def create() {
		def taxList = taxService.getAllTaxList();
		def estNumber = invoiceService.getEstNumber()
		def customerList = customerService.getCustomerListByUser()
		def itemList = itemService.getAllItemByUser()
		[estimateInstance: new Estimate(params), taxList : taxList, estNumber : estNumber, customerList : customerList, itemList : itemList]
	}

	def save() {
		def estimateInstance = new Estimate()
		estimateInstance.estNumber = NumberUtils.toInt(params?.estNumber)
		def customerInstance =  customerService.getCustomerById(params?.customerId)
		estimateInstance.customer = customerInstance
		estimateInstance.user = baseService.getLoggedInUser()
		
		
		estimateInstance.subTotal = params?.hiddenSubTotal as BigDecimal 
		estimateInstance.netTotal = params?.hiddenNetTotal as BigDecimal
		
		
		if(params?.estimateDate){
			estimateInstance.estimateDate = java.util.Date.parse("dd/MM/yyyy", params?.estimateDate)
		}
		if(params?.expireDate){
			estimateInstance.expireDate = java.util.Date.parse("dd/MM/yyyy", params?.expireDate)
		}
		

		estimateInstance.customerNotes = params?.customerNotes
		if(estimateInstance.validate()){
			invoiceService.saveEstimate(estimateInstance, params)
				flash.message = message(code: 'default.created.message')
		}else{
			def taxList = taxService.getAllTaxList();
			def customerList = customerService.getCustomerListByUser()
			def dbItemList = itemService.getAllItemByUser()
			render(view: "create", model: [estimateInstance : estimateInstance, taxList : taxList, customerList : customerList, itemList : dbItemList])
			return
		}

		flash.message = message(code: 'default.created.message')
		redirect(action: "estimateDetails", id : estimateInstance?.id)
	}


	def edit(Long id) {
		def estimateInstance = Estimate.read(id)
		
		if (!estimateInstance) {
			flash.message = message(code: 'default.not.found.message')
			redirect(action: "search")
			return
		}
		def taxList = taxService.getAllTaxList();
		def customerList = customerService.getCustomerListByUser()
		def dbItemList = itemService.getAllItemByUser()
		[estimateInstance: estimateInstance, taxList : taxList, customerList : customerList, itemList : dbItemList]
	}

	def update(Long id, Long version) {
		def estimateInstance = Estimate.read(id)
		def customerInstance =  customerService.getCustomerById(params?.customerId)
		estimateInstance.user = baseService.getLoggedInUser()
		estimateInstance.estNumber = NumberUtils.toInt(params?.estNumber)
		estimateInstance.customer = customerInstance
		
		estimateInstance.subTotal = params?.hiddenSubTotal as BigDecimal
		estimateInstance.netTotal = params?.hiddenNetTotal as BigDecimal
		if(params?.estimateDate){
			params.estimateDate = java.util.Date.parse("dd/MM/yyyy", params?.estimateDate)
		}
		if(params?.expireDate){
			params.expireDate = java.util.Date.parse("dd/MM/yyyy", params?.expireDate)
		}
		
		if (!estimateInstance) {
			flash.message = message(code: 'default.not.found.message')
			redirect(action: "search")
			return
		}
		
		estimateInstance.estimateDetails.clear()
		estimateInstance.estimateTaxTransactionDetails.clear()
		
		if (version != null) {
			if (estimateInstance.version > version) {
				estimateInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
						[
							message(code: 'customer.label', default: 'Customer')] as Object[],
						"Another user has updated this Customer while you were editing")
				def taxList = taxService.getAllTaxList();
				def customerList = customerService.getCustomerListByUser()
				def dbItemList = itemService.getAllItemByUser()
				render(view: "edit", model: [estimateInstance: estimateInstance, taxList : taxList, itemList : dbItemList, customerList : customerList])
				return
			}
		}

		estimateInstance.properties = params
		
		if (!estimateInstance.validate(flush: true)) {
			def taxList = taxService.getAllTaxList();
			def customerList = customerService.getCustomerListByUser()
			def dbItemList = itemService.getAllItemByUser()
			render(view: "edit", model: [estimateInstance: estimateInstance, taxList : taxList, taxList : taxList, itemList : dbItemList, customerList : customerList])
			return
		}else{
			invoiceService.saveEstimate(estimateInstance, params)
		}

		flash.message = message(code: 'default.updated.message')
		redirect(action: "edit", id: estimateInstance.id)
	}

	def printEstimate(){
		reportService?.generateEstimate(params)
		return
	}
	
	def delete(Long id) {
		def estimateInstance = Estimate.read(id)
		if (!estimateInstance) {
			flash.message = message(code: 'default.not.found.message')
			redirect(action: "search")
			return
		}

		try {
			estimateInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message')
			redirect(action: "search")
		}
		catch (DataIntegrityViolationException e) {
			flash.infoMessage = "Record can not be deleted, child reference is exsist."
			redirect(action: "search", id: id)
		}
	}


	def estimateDetails(Integer max){
		params.max = Math.min(max ?: 10, 100)
		def estimateInstance = Estimate.read(params?.id)
		[ estimateInstance : estimateInstance]
	}
}

grails-app/views/estimate/_dataList.gsp
<%@page import="com.billing.utility.PaymentType"%>
<%@ page import="com.billing.utility.InvoiceStatus" %>
<table class="table table-bordered data-table">
	<thead>
		<tr>
			<util:remoteSortableColumn action="search" onLoading="showSpinner(\'estimateListDiv\')" property="estNumber" update="estimateListDiv" title="Estimate#" defaultOrder="asc" params="[max:params?.max ?: 10, searchText : params?.searchText?:'']"/>
			<th style="text-align: left">Customer Name</th>
			<th style="text-align: right">Sub Total</th>
			<th style="text-align: right">Net Total</th>
			<th style="text-align: right">Estimate Date</th>
			<th style="text-align: right">Status</th>
			<th style="text-align: right">Payment Type</th>
			<th style="text-align: right">Actions</th>
		</tr>
	</thead>
	<tbody>
		<g:if test="${estimateInstanceList?.size() > 0 }">
				<g:each in="${estimateInstanceList}" var="estimateInstance" status="i">
					<tr class="gradeX">
						<td width="10%" style="text-align: center">${estimateInstance?.estNumber }</td>
						<td>${estimateInstance?.customer.customerName }</td>
						<td style="text-align: right" width="10%">${estimateInstance?.subTotal}</td>
						<td style="text-align: right" width="10%">${estimateInstance?.netTotal}</td>
						<td style="text-align: right" width="10%"><g:formatDate format='dd/MM/yyyy' date='${estimateInstance?.estimateDate}'/></td>
						<td width="10%" class="taskStatus">
							<g:if test="${estimateInstance?.estimateStatus == InvoiceStatus.Closed}">
								<span class="invoiced">${InvoiceStatus.Closed}</span>
							</g:if>
							<g:if test="${estimateInstance?.estimateStatus == InvoiceStatus.Open}">
								<span class="draft">${InvoiceStatus.Open}</span>
							</g:if>
							<g:if test="${estimateInstance?.estimateStatus == InvoiceStatus.Cancelled}">
								<span class="cancelled">${InvoiceStatus.Cancelled}</span>
							</g:if>
							<g:if test="${estimateInstance?.estimateStatus == InvoiceStatus.Overdue}">
								<span class="overdue">${InvoiceStatus.Overdue}</span>
							</g:if>
							<g:if test="${estimateInstance?.estimateStatus == InvoiceStatus.Refundable}">
								<span class="refundable">${InvoiceStatus.Refundable}</span>
							</g:if>
						</td>
						<td style="text-align: right" width="10%" >${estimateInstance?.paymentType}</td>
						<td width="5%">
							 <div class="btn-group">
									  <button class="btn btn-primary">Action</button>
									  <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
									  <ul class="dropdown-menu">
									  	<li><g:link action="edit" controller="estimate" id="${estimateInstance?.id}"><i class="icon-pencil"></i>&nbsp;Edit</g:link></li>
										<li><a href="#estimateDeleteAlert${i}" data-toggle="modal"><i class="icon-trash"></i>&nbsp;Delete</a></li>
										<li><g:link id="${estimateInstance?.id}" controller="invoice" action="convertToInvoice"><i class="icon-retweet"></i>&nbsp;Convert to Invoice</g:link></li>
										<li><g:link id="${estimateInstance?.id}" controller="estimate" action="estimateDetails"><i class="icon-th-list"></i>&nbsp;Details</g:link></li>
										<li><g:link id="${estimateInstance?.id}" controller="estimate" action="printEstimate"><i class="icon-print"></i>&nbsp;Print</g:link></li>
									  </ul>
								</div>
                                <div id="estimateDeleteAlert${i}" class="modal hide">
					              <div class="modal-header">
					                <button data-dismiss="modal" class="close" type="button">×</button>
					                <h3>Delete</h3>
					              </div>
					              <div class="modal-body">
					                <p>Once you choose to delete, the details of the estimate will be removed from the system forever and you will not be able to retrieve it later. Are you sure about deleting this estimate?</p>
					              </div>
					              <div class="modal-footer"> <g:link action="delete" id="${estimateInstance?.id}" class="btn btn-primary" href="#">Confirm</g:link> <a data-dismiss="modal" class="btn" href="#">Cancel</a> </div>
					            </div>
						</td>
					</tr>
				</g:each>
		</g:if>	
		<g:else>
			<tr class="gradeX">
				<td colspan="9" style="text-align: center">No record found</td>
			</tr>
		</g:else>		
	</tbody>
</table>
<div style="float:right" class="pagination">
<util:remotePaginate action="search" total="${estimateInstanceListTotal}" 
			update="estimateListDiv" max="${params?.max ?: 10 }" offset="${params?.offset }" params="[searchText : params?.searchText?:'']" onLoading="showSpinner(\'estimateListDiv\')"/>
</div>

grails-app/views/estimate/_estimate.gsp
<div class="content">

	<div class="page-header">
		<div class="icon">
			<span class="ico-dollar"></span>
		</div>
		<h3>
			Estimate #${estimateInstance?.estNumber} 
		</h3>
	</div>

	<div class="row-fluid">
		<div class="span12">

			<div class="block">
				<div class="data invoice">

					<div class="row-fluid">
						<div class="span3">
							<address>
								<strong>${estimateInstance?.user?.displayName}</strong>
								<g:if test="${estimateInstance?.user?.address1}">
								<br> ${estimateInstance?.user?.address1}
								</g:if>
								<g:if test="${estimateInstance?.user?.address2}">
								<br> ${estimateInstance?.user?.address2}
								</g:if>
								<g:if test="${estimateInstance?.user?.city}">
								<br>${estimateInstance?.user?.city}
								</g:if>
								<g:if test="${estimateInstance?.user?.mobileNumber}">
								<br>Mobile:	${estimateInstance?.user?.mobileNumber}
								</g:if>
							</address>
						</div>
						<div class="span3">
							<address>
								<strong>${estimateInstance?.customer?.customerName}</strong>
								<g:if test="${estimateInstance?.customer?.address1}">
								<br> ${estimateInstance?.customer?.address1}
								</g:if>
								<g:if test="${estimateInstance?.customer?.address2}">
								<br> ${estimateInstance?.customer?.address2} 
								</g:if>
								<g:if test="${estimateInstance?.customer?.city}">
								<br>${estimateInstance?.customer?.city}
								</g:if>
								<g:if test="${estimateInstance?.customer?.mobileNumber}">
								<br>Phone :  ${estimateInstance?.customer?.mobileNumber}
								</g:if>
							</address>
						</div>
						<div class="span3"></div>
						<div class="span3">
								<strong>Estimate Date:</strong> <g:formatDate format='dd/MM/yyyy' date='${estimateInstance?.estimateDate}'/><br>
								<strong>Expire Date:</strong> <g:formatDate format='dd/MM/yyyy' date='${estimateInstance?.expireDate}'/> 
							<div class="highlight">
								<strong>Estimate Amount:</strong> ${estimateInstance?.netTotal}  <em>INR</em>
							</div>
						</div>
					</div>

					<h4>Description</h4>
					<table class="table" width="100%">
						<thead>
							<tr>
								<th width="60%" style="text-align: left">Description</th>
								<th width="10%" style="text-align: right">Price</th>
								<th width="10%" style="text-align: right">Quantity</th>
								<th width="10%" style="text-align: right">Discount</th>
								<th width="10%" style="text-align: right">Tax1</th>
								<th width="10%" style="text-align: right">Tax2</th>
								<th width="10%" style="text-align: right">Tax3</th>
								<th width="10%" style="text-align: right">Total</th>
							</tr>
						</thead>
						<tbody>
						<g:each in="${estimateInstance?.estimateDetails}" var="detailsInstance">
							<tr>
								<td>${detailsInstance?.item?.itemName }</td>
								<td style="text-align: right">${detailsInstance?.rate}</td>
								<td style="text-align: right">${detailsInstance?.quantity}</td>
								<td style="text-align: right">${detailsInstance?.discountRate}%</td>
								<td style="text-align: right">${detailsInstance?.tax1 == null ? 'N/A' : detailsInstance?.tax1?.taxName + '@'+ detailsInstance?.tax1?.taxRate + '%'}</td>
								<td style="text-align: right">${detailsInstance?.tax2 == null ? 'N/A' : detailsInstance?.tax2?.taxName + '@'+ detailsInstance?.tax2?.taxRate + '%'}</td>
								<td style="text-align: right">${detailsInstance?.tax3 == null ? 'N/A' : detailsInstance?.tax3?.taxName + '@'+ detailsInstance?.tax3?.taxRate + '%'}</td>
								<td style="text-align: right">${detailsInstance?.total }</td>
							</tr>
						</g:each>	
						</tbody>
					</table>

					<div class="row-fluid">
						<div class="span9"></div>
						<div class="span3">
							<table class="table" width="100%">
								<tr ><td><span><b>Sub Total:</b></span></td><td style="text-align: right">${estimateInstance?.subTotal}</td></tr>
								<g:each in="${estimateInstance?.estimateTaxTransactionDetails}" var="taxTransactionInstance">
									<tr ><td><span>${taxTransactionInstance?.tax?.taxName + '@'+ taxTransactionInstance?.tax?.taxRate + '%'}:</span></td><td style="text-align: right">${taxTransactionInstance?.taxAmount}</td></tr>	
								</g:each>
								<tr class="highlight"><td><span><b>Net Total:</b></span></td><td style="text-align: right"> ${estimateInstance?.netTotal}</td></tr>
							</table>	
						</div>
					</div>

				</div>

			</div>

		</div>
	</div>

</div>

grails-app/views/estimate/_searchForm.gsp
<label class="control-label"><g:message code="tax.taxName.label"
		default="Invoice#" /></label>
<div class="controls">
	<input type="text" name="searchText"
		onkeyup="${remoteFunction(action: 'search',
						                       update: 'invoiceListDiv',
						                       params: '\'searchText=\' + this.value')}" />
</div>
<label class="control-label"><g:message code="tax.taxName.label"
		default="From" /></label>
<div class="controls">
	<input type="text" class="uptoTodayDatepicker" id="invoiceDate"
		name="invoiceDate" size="10"
		value="<g:formatDate format='dd/MM/yyyy' date='${invoiceInstance?.invoiceDate}'/>" />
</div>
<label class="control-label"><g:message code="tax.taxName.label"
		default="To" /></label>
<div class="controls">
	<input type="text" class="uptoTodayDatepicker" id="invoiceDate"
		name="invoiceDate" size="10"
		value="<g:formatDate format='dd/MM/yyyy' date='${invoiceInstance?.invoiceDate}'/>" />
</div>

grails-app/views/estimate/create.gsp
<%@page import="org.hibernate.event.def.OnLockVisitor"%>
<%@ page import="com.billing.domain.Tax" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="form">
		<g:set var="entityName" value="${message(code: 'tax.label', default: 'Tax')}" />
		<title>Add Estimate</title>
	</head>
	<body>
	<!-- End of content-header -->
			
               <div class="container-fluid">
				<div class="row-fluid">
					<div class="span12">
					
						 <g:if test="${flash.infoMessage}">
							<div class="alert alert-info">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Info!</strong> ${flash.infoMessage}
			          		 </div>
			             </g:if>   
			              <g:if test="${flash.errorMessage}">
							<div class="alert alert-error">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Error!</strong> ${flash.errorMessage}
			          		 </div>
			             </g:if>   
				         <g:if test="${flash.message}">
							<div class="alert alert-success">
					          <button class="close" data-dismiss="alert">×</button>
					          <strong>Success!</strong> ${flash.message }
					         </div>
			              </g:if>
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="icon-align-justify"></i>									
								</span>
								<h5>Create Estimate</h5>
							</div>
							<div class="widget-content nopadding">
								<g:form action="save" class="form-horizontal" name="estimateForm">
                                   <g:render template="form"></g:render>
                                   <div class="form-actions">
									     <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.save.label', default: 'Save')}" />
										<input type="button" onclick="window.location.href = '${createLink(action: 'search', controller: 'estimate')}'" class="btn btn-primary" value="${message(code: 'default.button.reset.label', default: 'Cancel')}" />
									 </div>  
                                </g:form>
                                <g:form name="customerPopupForm" action="saveCustomerPopupForEstimate" controller="customer" class="form-horizontal">
                                	<div class="modal hide" id="modal-add-event">
										 <div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">×</button>
											<h3>Add a new customer</h3>
										</div>
										<div class="modal-body">
											<div class="control-group  fieldcontain ${hasErrors(bean: customerInstance, field: 'customerName', 'error')}">
											     <label class="control-label"><g:message code="tax.taxName.label" default="Customer Name" /></label>
											     <div class="controls">
											         <input type="text" name="customerName" maxlength="100" value="${customerInstance?.customerName}" />
											         <span for="customerName" generated="true" class="help-inline"><g:fieldError bean="${customerInstance}" field="customerName"></g:fieldError></span>
											     </div>
											 </div>
											 <div class="control-group  fieldcontain ${hasErrors(bean: customerInstance, field: 'mobileNumber', 'error')}">
											     <label class="control-label"><g:message code="tax.taxName.label" default="Mobile#" /></label>
											     <div class="controls">
											         <input type="text" name="mobileNumber" id="mobileNumber" maxlength="30" value="${customerInstance?.mobileNumber}" />
											         <span for="mobileNumber" generated="true" class="help-inline"><g:fieldError bean="${customerInstance}" field="mobileNumber"></g:fieldError></span>
											     </div>
											 </div>
 
										</div>
										<div class="form-actions" style="text-align: right">
										    <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.save.label', default: 'Save')}" />
											<input type="button" data-dismiss="modal" onclick="window.location.href = '${createLink(action: 'create', controller: 'estimate')}'" class="btn btn-primary" value="${message(code: 'default.button.reset.label', default: 'Cancel')}" />
									 </div>  
									</div>
                                </g:form>
							</div>
						</div><!-- End of widget-box -->	
						
					</div><!-- End of span6 -->
			</div><!-- End of row-fluid -->
	</div><!-- End of container-fluid -->
	 <script type="text/javascript">
	$(document).ready(function(){
		
		// Form Validation
	    $("#customerPopupForm").validate({
			rules:{
				customerName:{
					required:true
				},
				officeNumber:{
					digits:true
				},
				mobileNumber:{
					required:true,
					digits:true
				}
			},
			messages:{
				customerName:"Please enter Customer Name.",
				mobileNumber:"Please enter Mobile Number."		
			},
			errorClass: "help-inline",
			errorElement: "span",
			highlight:function(element, errorClass, validClass) {
				$(element).parents('.control-group').addClass('error');
			},
			unhighlight: function(element, errorClass, validClass) {
				$(element).parents('.control-group').removeClass('error');
			}
		});
	});
		
	</script>
	</body>
</html>

grails-app/views/estimate/edit.gsp
<%@page import="org.hibernate.event.def.OnLockVisitor"%>
<%@ page import="com.billing.domain.Tax" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="form">
		<g:set var="entityName" value="${message(code: 'tax.label', default: 'Tax')}" />
		<title>Edit Estimate</title>
	</head>
	<body>
	<!-- End of content-header -->
			
               <div class="container-fluid">
				<div class="row-fluid">
					<div class="span12">
					
						 <g:if test="${flash.infoMessage}">
							<div class="alert alert-info">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Info!</strong> ${flash.infoMessage}
			          		 </div>
			             </g:if>   
				         <g:if test="${flash.message}">
							<div class="alert alert-success">
					          <button class="close" data-dismiss="alert">×</button>
					          <strong>Success!</strong> ${flash.message }
					         </div>
			              </g:if>
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="icon-align-justify"></i>									
								</span>
								<h5>Edit Estimate</h5>
							</div>
							<div class="widget-content nopadding">
								<g:form action="update" class="form-horizontal" name="invoiceForm">
								 	<g:hiddenField name="id" value="${estimateInstance?.id}" />
									<g:hiddenField name="version" value="${estimateInstance?.version}" />      
                                   <g:render template="form"></g:render>
                                   <div class="form-actions">
									     <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.save.label', default: 'Save')}" />
										<input type="button" onclick="window.location.href = '${createLink(action: 'search', controller: 'invoice')}'" class="btn btn-primary" value="${message(code: 'default.button.reset.label', default: 'Cancel')}" />
									 </div>  
                                </g:form>
							</div>
						</div><!-- End of widget-box -->	
						
						
					</div><!-- End of span6 -->
			</div><!-- End of row-fluid -->
	</div><!-- End of container-fluid -->
	</body>
</html>

grails-app/views/estimate/estimateDetails.gsp
<%@page import="org.hibernate.event.def.OnLockVisitor"%>
<%@ page import="com.billing.domain.Tax" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="form">
		<g:set var="entityName" value="${message(code: 'tax.label', default: 'Tax')}" />
		<title>Invoice Details</title>
	</head>
	<body>
	<!-- End of content-header -->
			
               <div class="container-fluid">
				<div class="row-fluid">
					<div class="span10">
					
						 <g:if test="${flash.infoMessage}">
							<div class="alert alert-info">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Info!</strong> ${flash.infoMessage}
			          		 </div>
			             </g:if>   
			              <g:if test="${flash.errorMessage}">
							<div class="alert alert-error">
						          <button class="close" data-dismiss="alert">×</button>
						          <strong>Error!</strong> ${flash.errorMessage}
			          		 </div>
			             </g:if>   
				         <g:if test="${flash.message}">
							<div class="alert alert-success">
					          <button class="close" data-dismiss="alert">×</button>
					          <strong>Success!</strong> ${flash.message }
					         </div>
			              </g:if>
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="icon-align-justify"></i>									
								</span>
								<span class="icon" style="float:right"><g:link action="search" controller="estimate" id="${estimateInstance?.id}"><i class="icon-arrow-left" title="Cancel"></i>&nbsp;</g:link></span>
								<span class="icon" style="float:right"><g:link action="printEstimate" controller="estimate" id="${estimateInstance?.id}"><i class="icon-print" title="Print"></i>&nbsp;</g:link></span>
								<span class="icon" style="float:right"><g:link action="edit" controller="estimate" id="${estimateInstance?.id}"><i class="icon-pencil" title="Edit"></i>&nbsp;</g:link></span>
								<span class="icon" style="float:right">&nbsp;</span>								
								<h5>Estimate Details</h5>
							</div>
							<g:form class="form-horizontal">
								<g:render template="estimate"></g:render>
							</g:form>
						</div><!-- End of widget-box -->
						<input type="button" onclick="window.location.href = '${createLink(action: 'search', controller: 'estimate')}'" class="btn btn-primary" value="${message(code: 'default.button.reset.label', default: 'Cancel')}" />
					</div><!-- End of span6 -->
			</div><!-- End of row-fluid -->
	</div><!-- End of container-fluid -->
	</body>
</html>